### ISSUE TITLE
Transaction Parsing

### ISSUE THREAD

**Issue by lmillik** [Ademan/Post#24]
I hooked all the pieces together (in a really clunky way) and borrowed the other subteam's products and transactions txt files. Everything seems to work correctly, but the transaction reader seems to be improperly parsing some entries. There are 7 transactions in the file and only 3 are created after reading the file. These are the 3 CREDIT transactions so that may be an issue. Another problem is that the reader specifies that a upc followed by no number in the transactions file should be counted as a single unit to be purchased. Our current TransactionReader treats these as customer name (I think) overwriting the real customer. I will commit and push the "integrated" version to the "Merging-TextReader" branch. Take a look.

**Comment by lmillik** [comment]
Also: oops, I just uploaded all the .class files.

**Comment by Ademan** [comment]
As we discussed in person, part of the issue was a missing $ in CASH and CHECK transactions. The other part was that my parser did not support UPCs without quantities. Both are resolved as of Friday.
